#!/bin/bash

set -e

BUILD_DIR=build

if [ ! -d "${BUILD_DIR}" ]; then
    echo "Making build dir"
    mkdir -p ${BUILD_DIR}

fi

echo "Changing to build dir"
pushd ${BUILD_DIR}

if [ ! -f "Makefile" ]; then
    echo "Configuring app"
    cmake .. $@
fi


PROCESSORS=`sysctl -n hw.ncpu`
make --no-print-directory -j$(($PROCESSORS * 2))

# run
if [ "$1" = "r" ]
then
        ./hamurabi
fi

popd
